//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remont
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentRepairDBEntities1 : DbContext
    {
        private static EquipmentRepairDBEntities1 _context;
        public EquipmentRepairDBEntities1()
            : base("name=EquipmentRepairDBEntities1")
        {
        }
        public static EquipmentRepairDBEntities1 GetContext()
        {
            if (_context == null)
                _context = new EquipmentRepairDBEntities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<FaultType> FaultType { get; set; }
        public virtual DbSet<RepairReport> RepairReport { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Technician> Technician { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
